name: heroku-elopio
version: "5.2.19"
summary: The Heroku CLI is used to manage Heroku apps from the command line.
description: |
  This is the next generation Go/Node-based Heroku CLI. Currently, it is not
  feature complete with the existing CLI and not intended to be used
  standalone.
confinement: strict

apps:
  heroku:
    command: bin/cli
    plugs: [network, network-bind]

parts:
  heroku-cli:
    source: https://github.com/heroku/cli.git
    plugin: go
    go-importpath: github.com/heroku/cli
