name: dcos-cli
version: "0.4.5"
summary: The command line for your datacenter!
description: |
  The DCOS Command Line Interface (CLI) is a cross-platform command line
  utility that provides a user-friendly yet powerful way to manage DCOS
  installations.
confinement: strict

apps:
  dcos:
    command: usr/bin/dcos
    plugs: [network]

parts:
  dcos-cli:
    source: https://github.com/dcos/dcos-cli.git
    source-tag: 0.4.5
    source-subdir: cli
    plugin: python3
