name: mirageos
version: 2.9.0
summary: MirageOS is a library operating system that constructs unikernels
description: |
  MirageOS is a library operating system that constructs unikernels for secure,
  high-performance network applications across a variety of cloud computing and
  mobile platforms. Code can be developed on a normal OS such as Linux or MacOS
  X, and then compiled into a fully-standalone, specialised unikernel that runs
  under the Xen hypervisor. Since Xen powers most public cloud computing
  infrastructure such as Amazon EC2 or Rackspace, this lets your servers run
  more cheaply, securely and with finer control than with a full software stack.
confinement: devmode

apps:
  mirage:
    command: bin/mirage

parts:
  mirage:
    plugin: mirage
    source: https://github.com/mirage/mirage
    source-type: git
    source-tag: v2.9.0
    build-packages:
      - build-essential
      - camlp4
      - m4
      - ocaml
      - ocaml-findlib
      - ocaml-native-compilers
      - opam

    opam-packages:
      - astring
      - functoria
      - ipaddr
      - logs
