name: shotwell
version: 0.23.1
summary: Shotwell photo manager
description: Shotwell is a photo manager for GNOME 3.
confinement: strict

apps:
  shotwell-git:
    command: gtk-launch shotwell
    plugs: [x11, unity7, home]

parts:
  shotwell:
    source: git://git.gnome.org/shotwell.git
    source-tag: shotwell-0.23.1
    plugin: autotools
    build-packages:
      - debhelper
      - desktop-file-utils
      - libatk1.0-dev
      - libexif-dev
      - libgee-0.8-dev
      - libgexiv2-dev
      - libglib2.0-dev
      - libgphoto2-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgtk-3-dev
      - libgudev-1.0-dev
      - libjson-glib-dev
      - libraw-dev
      - librest-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libunity-dev
      - libwebkit2gtk-4.0-dev
      - libxml2
      - m4
      - valac
      - gnome-doc-utils
    stage-packages:
      - libc6
      - libcairo2
      - libexif12
      - libgdk-pixbuf2.0-0
      - libgee-0.8-2
      - libgexiv2-2
      - libglib2.0-0
      - libgphoto2-6
      - libgphoto2-port12
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libgudev-1.0-0
      - libjson-glib-1.0-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libraw15
      - librest-0.7-0
      - libsoup2.4-1
      - libsqlite3-0
      - libunity9
      - libwebkit2gtk-4.0-37
      - libxml2
      - librsvg2-common
      - dbus-x11
      - dconf-tools
    after: [gtkconf]

