name: docker-compose
version: 1.8.0-rc2
summary: Define and run multi-container applications with Docker
description: |
  Compose is a tool for defining and running multi-container Docker
  applications. With Compose, you use a Compose file to configure your
  application's services. Then, using a single command, you create and start all
  the services from your configuration.
confinement: devmode

apps:
  compose:
    command: usr/bin/docker-compose

parts:
  compose:
    plugin: python3
    source: https://github.com/docker/compose
    source-type: git
    source-tag: 1.8.0-rc2
