name: leafpad
version: "1"
summary: GTK+ based simple text editor
description: |
   Leafpad is a simple GTK+ based text editor, the user interface is similar
   to Notepad. It aims to be lighter than GEdit and KWrite, and to be as
   useful as them.
confinement: devmode

apps:
  leafpad:
    command: gtk-launch leafpad
    plugs: [home, unity7, opengl, network, x11]

parts:
  leafpad:
    source: https://github.com/oluc/leafpad.git
    plugin: autotools
    snap:
      - -usr/share/doc
    build-packages:
      - build-essential
      - libgtk2.0-dev
      - intltool
    stage-packages:
      - fontconfig-config
      - libgtk2.0-bin
    after: [gtkconf]

