name: deis-workflow-cli
version: "2.0.0"
summary: The CLI for Deis Workflow
description: |
  deis is a command line utility used to interact with the Deis open source
  PaaS.
confinement: strict

apps:
  deis:
    command: bin/workflow-cli
    plugs: [network, network-bind]

parts:
  workflow-cli:
    source: https://github.com/deis/workflow-cli.git
    plugin: go
    go-importpath: github.com/deis/workflow-cli
