name: atom
version: "1.8.0"
summary: Atom Text Editor
description: Atom Text editor, from GitHub
confinement: devmode

apps:
  atom:
    command: bin/wrapper
    plugs: [home, x11, unity7, gsettings, opengl, pulseaudio, network]

parts:
  atom:
    source: https://github.com/atom/atom/archive/v1.8.0.tar.gz
    plugin: grunt
    gruntfile: build/Gruntfile.coffee
    build-packages: [build-essential, git, libgnome-keyring-dev]
    stage-packages:
      - gconf-service
      - gconf2
      - git
      - gvfs-bin
      - libasound2
      - libcap2
      - libgcrypt20
      - libgtk2.0-0
      - libnotify4
      - libnss3
      - libudev1
      - libxtst6
      - python
      - xdg-utils
      - unity-gtk2-module
  atom-copy:
    source: .
    plugin: copy
    files:
      wrapper: bin/wrapper
