name: atom
version: "1.9.0"
summary: Atom Text Editor
description: Atom Text editor, from GitHub
confinement: strict

apps:
  atom:
    command: bin/wrapper
    plugs: [home]

parts:
  atom:
    source: git://github.com/atom/atom
    plugin: nodejs
    gruntfile: build/Gruntfile.coffee
    build-packages: [build-essential, git, libgnome-keyring-dev, fakeroot]
    stage-packages:
      - git
      - gconf2
      - gconf-service
      - libgtk2.0-0
      - libudev1
      - libgcrypt20
      - libnotify4
      - libxtst6
      - libnss3
      - python
      - gvfs-bin
      - xdg-utils
      - libcap2
  atom-copy:
    source: .
    plugin: copy
    files:
      wrapper: bin/wrapper
