name: openjdk-demo
version: "1.0"
summary: OpenJDK Swing Example Applications
description: OpenJDK Swing Example Applications
confinement: strict

apps:
  FileChooser:
    command: bin/FileChooserDemo.sh
    plugs: [unity7, network, home]

parts:
  openjdk-demo:
    plugin: copy
    files:
      FileChooserDemo.sh: bin/FileChooserDemo.sh
  java:
    plugin: nil
    stage-packages: [openjdk-8-jre, openjdk-8-demo]
